import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { connectionsQuiz } from '../../test/connectionsFixtures'
import { DemoGameRepository } from './DemoGameRepository'
import { defaultLaunchGameSettings } from '../../features/game/launchSettings'
import { parseSafeGameState } from '../supabase/safeGameState'
import { teamStandings } from '../../features/teams/teams'

beforeEach(() => { localStorage.clear(); vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-04T13:00:00Z')) })
afterEach(() => vi.useRealTimers())

it.each(['individual', 'teams'] as const)('plays shared clues in %s, with privacy, one guess, rounds and restart', async playMode => {
  const repo = new DemoGameRepository(), source = connectionsQuiz()
  source.questions.push({ ...structuredClone(source.questions[0]), id: 'next-connection', roundId: 'round-2', displayOrder: 1 })
  source.rounds.push({ ...source.rounds[0], id: 'round-2', title: 'Round 2', introEnabled: true, displayOrder: 1 })
  const quiz = await repo.saveQuiz(source), session = await repo.launchGame(quiz.id, { ...defaultLaunchGameSettings(quiz), playMode, teamNames: ['Blue', 'Red'], teamAssignmentMode: 'host', autoLockWhenAllAnswered: false })
  const early = await repo.joinRoom(session.roomCode, 'Early'), late = await repo.joinRoom(session.roomCode, 'Late'), wrong = await repo.joinRoom(session.roomCode, 'Wrong')
  if (playMode === 'teams') for (const p of [early, late, wrong]) await repo.assignPlayerTeam(session.id, p.player.id, session.teams![0].id)
  const state = async () => parseSafeGameState(await repo.getSafeGameState(session.roomCode))
  const action = (kind: Parameters<DemoGameRepository['changePhase']>[1]) => repo.changePhase(session.id, kind)
  const answer = (p: typeof early, value: string) => repo.submitAnswer(session.roomCode, p.player.id, p.reconnectToken, { type: 'connections', value })
  await expect(repo.revealConnectionClue(session.id)).rejects.toThrow()
  await action('start')
  const first = await state()
  vi.setSystemTime(Date.parse(first.questionOpenedAt!) + 1000)
  expect(first.currentQuestion).toMatchObject({ revealedClueCount: 1, availablePoints: 1000, visibleClues: [{ text: 'Mercury' }] })
  expect(JSON.stringify(first)).not.toMatch(/Venus|Earth|Mars|"correctAnswer"|acceptedAnswers|Planets/)
  await answer(early, 'Planets'); await answer(wrong, 'Stars')
  await repo.revealConnectionClue(session.id)
  expect((await state()).currentQuestion).toMatchObject({ revealedClueCount: 2, availablePoints: 750 })
  await expect(answer(wrong, 'Planets')).rejects.toThrow(/already/)
  await repo.revealConnectionClue(session.id)
  await repo.reconnectPlayer({ playerId: late.player.id, reconnectToken: late.reconnectToken, nickname: 'Late', roomCode: session.roomCode })
  const third = await state()
  expect(third.currentQuestion).toMatchObject({ revealedClueCount: 3, availablePoints: 500 })
  expect(third.questionOpenedAt).toBe(first.questionOpenedAt); expect(third.questionClosesAt).toBe(first.questionClosesAt)
  expect(JSON.stringify(third)).not.toContain('Mars')
  vi.setSystemTime(Date.parse(first.questionOpenedAt!) + 50000)
  await answer(late, 'PLANETS OF THE SOLAR SYSTEM!')
  await action('lock')
  expect(JSON.stringify(await state())).not.toContain('Mars')
  await expect(repo.revealConnectionClue(session.id)).rejects.toThrow()
  await action('reveal')
  expect((await state()).currentQuestion).toMatchObject({ revealedClueCount: 4 })
  expect((await state()).reveal).toMatchObject({ correctAnswer: 'Planets', correctPlayerIds: [early.player.id, late.player.id] })
  expect(JSON.stringify(await state())).not.toContain('acceptedAnswers')
  await action('leaderboard')
  const board = await state()
  expect(board.leaderboard.map(p => p.totalScore)).toEqual([1000, 500, 0])
  if (playMode === 'teams') expect(teamStandings(board.teams!, board.players, board.leaderboard)[0].totalScore).toBe(1500)
  await action('next'); expect((await state()).currentQuestion).toBeNull()
  expect((await repo.getHostLiveSession(session.id))!.connectionClueCount).toBe(0)
  await action('start-round'); expect((await state()).currentQuestion).toMatchObject({ revealedClueCount: 1 })
  vi.setSystemTime(Date.parse((await state()).questionOpenedAt!))
  await action('finish'); await action('restart')
  expect((await repo.getHostLiveSession(session.id))!.connectionClueCount).toBe(0)
  await action('start'); expect((await state()).currentQuestion).toMatchObject({ revealedClueCount: 1 })
})

it('caps the final clue and rejects reveals at the deadline without extending the timer', async () => {
  const repo = new DemoGameRepository(), quiz = await repo.saveQuiz(connectionsQuiz()), session = await repo.launchGame(quiz.id)
  await repo.changePhase(session.id, 'start')
  const before = (await repo.getSafeGameState(session.roomCode))!
  vi.setSystemTime(Date.parse(before.questionOpenedAt!))
  for (let i = 0; i < 3; i++) await repo.revealConnectionClue(session.id)
  await expect(repo.revealConnectionClue(session.id)).rejects.toThrow()
  expect((await repo.getSafeGameState(session.roomCode))?.questionClosesAt).toBe(before.questionClosesAt)
  vi.setSystemTime(Date.parse(before.questionClosesAt!))
  await expect(repo.revealConnectionClue(session.id)).rejects.toThrow()
})
